package com.minipos.core.backup

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import android.util.Log
import com.minipos.data.database.MiniPosDatabase
import com.minipos.data.database.entity.*
import com.minipos.data.preferences.AppPreferences
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.*
import java.security.KeyStore
import java.text.SimpleDateFormat
import java.util.*
import java.util.zip.GZIPInputStream
import java.util.zip.GZIPOutputStream
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Manages encrypted local backups of the miniPOS database.
 *
 * Format: [12-byte IV][GZipped JSON payload] — all AES-256-GCM encrypted,
 * then Base64-encoded and written to a .mpos file.
 *
 * The encryption key is stored in Android Keystore (never leaves secure hardware).
 */
@Singleton
class BackupManager @Inject constructor(
    @ApplicationContext private val context: Context,
    private val database: MiniPosDatabase,
    private val appPreferences: AppPreferences,
) {
    companion object {
        private const val TAG = "BackupManager"
        private const val KEY_ALIAS = "minipos_backup_key"
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val BACKUP_VERSION = 2
        private const val BACKUP_FILE_EXT = ".mpos"
    }

    // ─── Key management via Android Keystore ─────────────────────────────────

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        if (keyStore.containsAlias(KEY_ALIAS)) {
            return (keyStore.getEntry(KEY_ALIAS, null) as KeyStore.SecretKeyEntry).secretKey
        }
        val keyGen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
        keyGen.init(
            KeyGenParameterSpec.Builder(
                KEY_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setUserAuthenticationRequired(false)
                .build(),
        )
        return keyGen.generateKey()
    }

    // ─── Encryption / Decryption ─────────────────────────────────────────────

    private fun encrypt(plainText: ByteArray): ByteArray {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv // 12 bytes generated by GCM
        val cipherText = cipher.doFinal(plainText)
        return iv + cipherText
    }

    private fun decrypt(data: ByteArray): ByteArray {
        val key = getOrCreateKey()
        val iv = data.copyOfRange(0, GCM_IV_LENGTH)
        val cipherText = data.copyOfRange(GCM_IV_LENGTH, data.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(128, iv))
        return cipher.doFinal(cipherText)
    }

    // ─── Compress / Decompress ───────────────────────────────────────────────

    private fun gzip(data: ByteArray): ByteArray {
        val bos = ByteArrayOutputStream()
        GZIPOutputStream(bos).use { it.write(data) }
        return bos.toByteArray()
    }

    private fun gunzip(data: ByteArray): ByteArray {
        return GZIPInputStream(ByteArrayInputStream(data)).use { it.readBytes() }
    }

    // ─── Public API ──────────────────────────────────────────────────────────

    /**
     * Creates an encrypted backup file in the app's private backup directory.
     * Returns [BackupResult] with the file path and metadata on success.
     */
    suspend fun createBackup(): BackupResult = withContext(Dispatchers.IO) {
        try {
            Log.d(TAG, "Starting backup…")
            val json = exportToJson()
            val jsonBytes = json.toByteArray(Charsets.UTF_8)
            val compressed = gzip(jsonBytes)
            val encrypted = encrypt(compressed)
            val encoded = Base64.encodeToString(encrypted, Base64.NO_WRAP)

            val backupDir = getBackupDir()
            val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US).format(Date())
            val file = File(backupDir, "minipos_backup_$timestamp$BACKUP_FILE_EXT")
            file.writeText(encoded, Charsets.UTF_8)

            val sizeMb = file.length() / 1024.0 / 1024.0
            Log.d(TAG, "Backup created: ${file.name} (${String.format("%.2f", sizeMb)} MB)")

            BackupResult.Success(
                filePath = file.absolutePath,
                fileName = file.name,
                createdAt = System.currentTimeMillis(),
                sizeBytes = file.length(),
            )
        } catch (e: Exception) {
            Log.e(TAG, "Backup failed", e)
            BackupResult.Error(e.message ?: "Unknown backup error")
        }
    }

    /**
     * Restores data from an encrypted backup file.
     * WARNING: this REPLACES all local data.
     */
    suspend fun restoreBackup(filePath: String): RestoreResult = withContext(Dispatchers.IO) {
        try {
            Log.d(TAG, "Starting restore from $filePath…")
            val encoded = File(filePath).readText(Charsets.UTF_8)
            val encrypted = Base64.decode(encoded, Base64.NO_WRAP)
            val compressed = decrypt(encrypted)
            val jsonBytes = gunzip(compressed)
            val json = String(jsonBytes, Charsets.UTF_8)

            val root = JSONObject(json)
            val version = root.optInt("backupVersion", 1)
            Log.d(TAG, "Restoring backup version $version")

            importFromJson(root)

            Log.d(TAG, "Restore completed successfully")
            RestoreResult.Success
        } catch (e: Exception) {
            Log.e(TAG, "Restore failed", e)
            RestoreResult.Error(e.message ?: "Unknown restore error")
        }
    }

    /** Lists available backup files from the app's private backup directory, newest first. */
    fun listBackups(): List<BackupFileInfo> {
        return getBackupDir()
            .listFiles { f -> f.extension == "mpos" }
            ?.sortedByDescending { it.lastModified() }
            ?.map {
                BackupFileInfo(
                    filePath = it.absolutePath,
                    fileName = it.name,
                    createdAt = it.lastModified(),
                    sizeBytes = it.length(),
                )
            }
            ?: emptyList()
    }

    /** Deletes a backup file. */
    fun deleteBackup(filePath: String): Boolean {
        return try {
            File(filePath).delete()
        } catch (_: Exception) {
            false
        }
    }

    private fun getBackupDir(): File {
        val dir = File(context.filesDir, "backups")
        if (!dir.exists()) dir.mkdirs()
        return dir
    }

    // ─── Serialization ───────────────────────────────────────────────────────

    private suspend fun exportToJson(): String {
        val store = database.storeDao().getStore()
            ?: throw IllegalStateException("No store found")
        val storeId = store.id
        val deviceId = appPreferences.getDeviceIdSync()

        val root = JSONObject()
        root.put("backupVersion", BACKUP_VERSION)
        root.put("storeId", storeId)
        root.put("createdAt", System.currentTimeMillis())
        root.put("deviceId", deviceId)

        // Store
        root.put("store", storeEntityToJson(store))

        // Users — include PIN hashes for full restore capability
        val usersArr = JSONArray()
        database.userDao().getAllUsers(storeId).forEach { u ->
            usersArr.put(userEntityToJson(u, includeSecrets = true))
        }
        root.put("users", usersArr)

        // Categories
        val catsArr = JSONArray()
        database.categoryDao().getAll(storeId).forEach { c ->
            catsArr.put(categoryEntityToJson(c))
        }
        // Also include soft-deleted to fully restore
        root.put("categories", catsArr)

        // Suppliers
        val suppliersArr = JSONArray()
        database.supplierDao().getAll(storeId).forEach { s ->
            suppliersArr.put(supplierEntityToJson(s))
        }
        root.put("suppliers", suppliersArr)

        // Products
        val productsArr = JSONArray()
        database.productDao().getAll(storeId).forEach { p ->
            productsArr.put(productEntityToJson(p))
        }
        root.put("products", productsArr)

        // Product Variants
        val variantsArr = JSONArray()
        database.productVariantDao().let { dao ->
            // get all products including those with variants
            database.productDao().getAll(storeId).forEach { p ->
                if (p.hasVariants) {
                    dao.getByProductId(p.id).forEach { v ->
                        variantsArr.put(variantEntityToJson(v))
                    }
                }
            }
        }
        root.put("productVariants", variantsArr)

        // Customers
        val customersArr = JSONArray()
        database.customerDao().getAll(storeId).forEach { c ->
            customersArr.put(customerEntityToJson(c))
        }
        root.put("customers", customersArr)

        // Inventory
        val inventoryArr = JSONArray()
        database.inventoryDao().observeAllInventory(storeId).let { flow ->
            // Use a direct query for backup
            database.inventoryDao().let { dao ->
                // We use getAllStockWithProduct but we need raw entities; use direct method
                // Collected via a synchronous helper
                inventoryArr.apply { /* populated below via raw SQL */ }
            }
        }
        // Fallback: build inventory JSON from stock overview
        val stockList = database.inventoryDao().getAllStockWithProduct(storeId)
        stockList.forEach { sw ->
            val obj = JSONObject()
            obj.put("id", sw.id)
            obj.put("storeId", sw.storeId)
            obj.put("productId", sw.productId)
            obj.put("variantId", sw.variantId ?: JSONObject.NULL)
            obj.put("quantity", sw.quantity)
            obj.put("reservedQty", sw.reservedQty)
            inventoryArr.put(obj)
        }
        root.put("inventory", inventoryArr)

        // Orders (last 12 months)
        val cutoff = System.currentTimeMillis() - (365L * 24 * 3600 * 1000)
        val ordersArr = JSONArray()
        database.orderDao().getOrdersByDateRange(storeId, cutoff, System.currentTimeMillis()).forEach { o ->
            val orderObj = orderEntityToJson(o)
            // Items
            val itemsArr = JSONArray()
            database.orderDao().getOrderItems(o.id).forEach { i ->
                itemsArr.put(orderItemEntityToJson(i))
            }
            orderObj.put("items", itemsArr)
            // Payments
            val paymentsArr = JSONArray()
            database.orderDao().getOrderPayments(o.id).forEach { p ->
                paymentsArr.put(orderPaymentEntityToJson(p))
            }
            orderObj.put("payments", paymentsArr)
            ordersArr.put(orderObj)
        }
        root.put("orders", ordersArr)

        // Purchase Orders (last 12 months)
        val purchaseOrdersArr = JSONArray()
        database.purchaseOrderDao().getByDateRange(storeId, cutoff, System.currentTimeMillis()).forEach { po ->
            val poObj = purchaseOrderEntityToJson(po)
            val poItemsArr = JSONArray()
            database.purchaseOrderDao().getItemsByOrderId(po.id).forEach { poi ->
                poItemsArr.put(purchaseOrderItemEntityToJson(poi))
            }
            poObj.put("items", poItemsArr)
            purchaseOrdersArr.put(poObj)
        }
        root.put("purchaseOrders", purchaseOrdersArr)

        return root.toString()
    }

    private suspend fun importFromJson(root: JSONObject) {
        val storeJson = root.getJSONObject("store")
        val storeId = storeJson.getString("id")
        val now = System.currentTimeMillis()
        val deviceId = appPreferences.getDeviceIdSync()

        // 1. Restore store
        val storeEntity = jsonToStoreEntity(storeJson, deviceId)
        database.storeDao().insert(storeEntity)

        // 2. Restore users (with full PIN hashes)
        val usersArr = root.optJSONArray("users")
        if (usersArr != null) {
            for (i in 0 until usersArr.length()) {
                database.userDao().insert(jsonToUserEntity(usersArr.getJSONObject(i), storeId, deviceId, now))
            }
        }

        // 3. Restore categories
        val catsArr = root.optJSONArray("categories")
        if (catsArr != null) {
            for (i in 0 until catsArr.length()) {
                database.categoryDao().insert(jsonToCategoryEntity(catsArr.getJSONObject(i), storeId, deviceId, now))
            }
        }

        // 4. Restore suppliers
        val suppliersArr = root.optJSONArray("suppliers")
        if (suppliersArr != null) {
            for (i in 0 until suppliersArr.length()) {
                database.supplierDao().insert(jsonToSupplierEntity(suppliersArr.getJSONObject(i), storeId, deviceId, now))
            }
        }

        // 5. Restore products
        val productsArr = root.optJSONArray("products")
        if (productsArr != null) {
            for (i in 0 until productsArr.length()) {
                database.productDao().insert(jsonToProductEntity(productsArr.getJSONObject(i), storeId, deviceId, now))
            }
        }

        // 6. Restore product variants
        val variantsArr = root.optJSONArray("productVariants")
        if (variantsArr != null) {
            for (i in 0 until variantsArr.length()) {
                database.productVariantDao().insert(jsonToVariantEntity(variantsArr.getJSONObject(i), storeId, deviceId, now))
            }
        }

        // 7. Restore customers
        val customersArr = root.optJSONArray("customers")
        if (customersArr != null) {
            for (i in 0 until customersArr.length()) {
                database.customerDao().insert(jsonToCustomerEntity(customersArr.getJSONObject(i), storeId, deviceId, now))
            }
        }

        // 8. Restore inventory
        val inventoryArr = root.optJSONArray("inventory")
        if (inventoryArr != null) {
            for (i in 0 until inventoryArr.length()) {
                val obj = inventoryArr.getJSONObject(i)
                val entity = InventoryEntity(
                    id = obj.getString("id"),
                    storeId = storeId,
                    productId = obj.getString("productId"),
                    variantId = obj.optString("variantId").takeIf { it.isNotEmpty() && it != "null" },
                    quantity = obj.getDouble("quantity"),
                    reservedQty = obj.optDouble("reservedQty", 0.0),
                    createdAt = now,
                    updatedAt = now,
                    deviceId = deviceId,
                )
                database.inventoryDao().insert(entity)
            }
        }

        // 9. Restore orders
        val ordersArr = root.optJSONArray("orders")
        if (ordersArr != null) {
            for (i in 0 until ordersArr.length()) {
                val o = ordersArr.getJSONObject(i)
                database.orderDao().insertOrder(jsonToOrderEntity(o, storeId, deviceId))
                val itemsArr = o.optJSONArray("items")
                if (itemsArr != null) {
                    val items = (0 until itemsArr.length()).map { j ->
                        jsonToOrderItemEntity(itemsArr.getJSONObject(j), deviceId)
                    }
                    if (items.isNotEmpty()) database.orderDao().insertOrderItems(items)
                }
                val paymentsArr = o.optJSONArray("payments")
                if (paymentsArr != null) {
                    val payments = (0 until paymentsArr.length()).map { j ->
                        jsonToOrderPaymentEntity(paymentsArr.getJSONObject(j), deviceId)
                    }
                    if (payments.isNotEmpty()) database.orderDao().insertOrderPayments(payments)
                }
            }
        }

        // 10. Restore purchase orders
        val poArr = root.optJSONArray("purchaseOrders")
        if (poArr != null) {
            for (i in 0 until poArr.length()) {
                val po = poArr.getJSONObject(i)
                database.purchaseOrderDao().insert(jsonToPurchaseOrderEntity(po, storeId, deviceId))
                val poItemsArr = po.optJSONArray("items")
                if (poItemsArr != null) {
                    val items = (0 until poItemsArr.length()).map { j ->
                        jsonToPurchaseOrderItemEntity(poItemsArr.getJSONObject(j), deviceId)
                    }
                    if (items.isNotEmpty()) database.purchaseOrderDao().insertItems(items)
                }
            }
        }
    }

    // ─── Entity → JSON helpers ────────────────────────────────────────────────

    private fun storeEntityToJson(e: StoreEntity) = JSONObject().apply {
        put("id", e.id)
        put("name", e.name)
        put("code", e.code)
        put("address", e.address ?: JSONObject.NULL)
        put("phone", e.phone ?: JSONObject.NULL)
        put("settings", e.settings ?: JSONObject.NULL)
        put("currency", e.currency)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun userEntityToJson(e: UserEntity, includeSecrets: Boolean) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("displayName", e.displayName)
        put("role", e.role)
        put("isActive", e.isActive)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
        if (includeSecrets) {
            put("pinHash", e.pinHash)
            put("passwordHash", e.passwordHash ?: JSONObject.NULL)
        }
    }

    private fun categoryEntityToJson(e: CategoryEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("name", e.name)
        put("parentId", e.parentId ?: JSONObject.NULL)
        put("description", e.description ?: JSONObject.NULL)
        put("icon", e.icon ?: JSONObject.NULL)
        put("color", e.color ?: JSONObject.NULL)
        put("sortOrder", e.sortOrder)
        put("isActive", e.isActive)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun supplierEntityToJson(e: SupplierEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("name", e.name)
        put("contactPerson", e.contactPerson ?: JSONObject.NULL)
        put("phone", e.phone ?: JSONObject.NULL)
        put("mobile", e.mobile ?: JSONObject.NULL)
        put("email", e.email ?: JSONObject.NULL)
        put("address", e.address ?: JSONObject.NULL)
        put("taxCode", e.taxCode ?: JSONObject.NULL)
        put("paymentTerm", e.paymentTerm ?: JSONObject.NULL)
        put("bankName", e.bankName ?: JSONObject.NULL)
        put("bankAccount", e.bankAccount ?: JSONObject.NULL)
        put("bankAccountHolder", e.bankAccountHolder ?: JSONObject.NULL)
        put("notes", e.notes ?: JSONObject.NULL)
        put("isActive", e.isActive)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun productEntityToJson(e: ProductEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("categoryId", e.categoryId ?: JSONObject.NULL)
        put("supplierId", e.supplierId ?: JSONObject.NULL)
        put("sku", e.sku)
        put("barcode", e.barcode ?: JSONObject.NULL)
        put("name", e.name)
        put("description", e.description ?: JSONObject.NULL)
        put("costPrice", e.costPrice)
        put("sellingPrice", e.sellingPrice)
        put("unit", e.unit)
        put("imagePath", e.imagePath ?: JSONObject.NULL)
        put("additionalImages", e.additionalImages ?: JSONObject.NULL)
        put("minStock", e.minStock)
        put("maxStock", e.maxStock ?: JSONObject.NULL)
        put("isActive", e.isActive)
        put("trackInventory", e.trackInventory)
        put("taxRate", e.taxRate)
        put("hasVariants", e.hasVariants)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun variantEntityToJson(e: ProductVariantEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("productId", e.productId)
        put("variantName", e.variantName)
        put("sku", e.sku)
        put("barcode", e.barcode ?: JSONObject.NULL)
        put("costPrice", e.costPrice ?: JSONObject.NULL)
        put("sellingPrice", e.sellingPrice ?: JSONObject.NULL)
        put("attributes", e.attributes)
        put("isActive", e.isActive)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun customerEntityToJson(e: CustomerEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("name", e.name)
        put("phone", e.phone ?: JSONObject.NULL)
        put("email", e.email ?: JSONObject.NULL)
        put("address", e.address ?: JSONObject.NULL)
        put("notes", e.notes ?: JSONObject.NULL)
        put("totalSpent", e.totalSpent)
        put("visitCount", e.visitCount)
        put("lastVisitAt", e.lastVisitAt ?: JSONObject.NULL)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun orderEntityToJson(e: OrderEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("orderCode", e.orderCode)
        put("customerId", e.customerId ?: JSONObject.NULL)
        put("customerName", e.customerName ?: JSONObject.NULL)
        put("customerPhone", e.customerPhone ?: JSONObject.NULL)
        put("subtotal", e.subtotal)
        put("discountType", e.discountType ?: JSONObject.NULL)
        put("discountValue", e.discountValue)
        put("discountAmount", e.discountAmount)
        put("taxAmount", e.taxAmount)
        put("totalAmount", e.totalAmount)
        put("status", e.status)
        put("notes", e.notes ?: JSONObject.NULL)
        put("createdBy", e.createdBy)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun orderItemEntityToJson(e: OrderItemEntity) = JSONObject().apply {
        put("id", e.id)
        put("orderId", e.orderId)
        put("productId", e.productId)
        put("variantId", e.variantId ?: JSONObject.NULL)
        put("productName", e.productName)
        put("variantName", e.variantName ?: JSONObject.NULL)
        put("quantity", e.quantity)
        put("unitPrice", e.unitPrice)
        put("costPrice", e.costPrice)
        put("discountType", e.discountType ?: JSONObject.NULL)
        put("discountValue", e.discountValue)
        put("discountAmount", e.discountAmount)
        put("taxAmount", e.taxAmount)
        put("totalPrice", e.totalPrice)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun orderPaymentEntityToJson(e: OrderPaymentEntity) = JSONObject().apply {
        put("id", e.id)
        put("orderId", e.orderId)
        put("method", e.method)
        put("amount", e.amount)
        put("receivedAmount", e.receivedAmount ?: JSONObject.NULL)
        put("changeAmount", e.changeAmount)
        put("referenceNo", e.referenceNo ?: JSONObject.NULL)
        put("notes", e.notes ?: JSONObject.NULL)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun purchaseOrderEntityToJson(e: PurchaseOrderEntity) = JSONObject().apply {
        put("id", e.id)
        put("storeId", e.storeId)
        put("code", e.code)
        put("supplierId", e.supplierId ?: JSONObject.NULL)
        put("supplierName", e.supplierName ?: JSONObject.NULL)
        put("totalAmount", e.totalAmount)
        put("totalItems", e.totalItems)
        put("notes", e.notes ?: JSONObject.NULL)
        put("status", e.status)
        put("createdBy", e.createdBy)
        put("confirmedAt", e.confirmedAt ?: JSONObject.NULL)
        put("isDeleted", e.isDeleted)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    private fun purchaseOrderItemEntityToJson(e: PurchaseOrderItemEntity) = JSONObject().apply {
        put("id", e.id)
        put("purchaseOrderId", e.purchaseOrderId)
        put("productId", e.productId)
        put("variantId", e.variantId ?: JSONObject.NULL)
        put("productName", e.productName)
        put("variantName", e.variantName ?: JSONObject.NULL)
        put("quantity", e.quantity)
        put("unitCost", e.unitCost)
        put("totalCost", e.totalCost)
        put("createdAt", e.createdAt)
        put("updatedAt", e.updatedAt)
    }

    // ─── JSON → Entity helpers ────────────────────────────────────────────────

    private fun jsonToStoreEntity(o: JSONObject, deviceId: String) = StoreEntity(
        id = o.getString("id"),
        name = o.getString("name"),
        code = o.getString("code"),
        address = o.optString("address").takeIf { it.isNotEmpty() && it != "null" },
        phone = o.optString("phone").takeIf { it.isNotEmpty() && it != "null" },
        settings = o.optString("settings").takeIf { it.isNotEmpty() && it != "null" },
        currency = o.optString("currency", "VND"),
        createdAt = o.getLong("createdAt"),
        updatedAt = o.getLong("updatedAt"),
        deviceId = deviceId,
    )

    private fun jsonToUserEntity(o: JSONObject, storeId: String, deviceId: String, now: Long) = UserEntity(
        id = o.getString("id"),
        storeId = storeId,
        displayName = o.getString("displayName"),
        role = o.getString("role"),
        pinHash = o.optString("pinHash", ""),
        passwordHash = o.optString("passwordHash").takeIf { it.isNotEmpty() && it != "null" },
        isActive = o.optBoolean("isActive", true),
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.optLong("createdAt", now),
        updatedAt = o.optLong("updatedAt", now),
        deviceId = deviceId,
    )

    private fun jsonToCategoryEntity(o: JSONObject, storeId: String, deviceId: String, now: Long) = CategoryEntity(
        id = o.getString("id"),
        storeId = storeId,
        name = o.getString("name"),
        parentId = o.optString("parentId").takeIf { it.isNotEmpty() && it != "null" },
        description = o.optString("description").takeIf { it.isNotEmpty() && it != "null" },
        icon = o.optString("icon").takeIf { it.isNotEmpty() && it != "null" },
        color = o.optString("color").takeIf { it.isNotEmpty() && it != "null" },
        sortOrder = o.optInt("sortOrder", 0),
        isActive = o.optBoolean("isActive", true),
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.optLong("createdAt", now),
        updatedAt = o.optLong("updatedAt", now),
        deviceId = deviceId,
    )

    private fun jsonToSupplierEntity(o: JSONObject, storeId: String, deviceId: String, now: Long) = SupplierEntity(
        id = o.getString("id"),
        storeId = storeId,
        name = o.getString("name"),
        contactPerson = o.optString("contactPerson").takeIf { it.isNotEmpty() && it != "null" },
        phone = o.optString("phone").takeIf { it.isNotEmpty() && it != "null" },
        mobile = o.optString("mobile").takeIf { it.isNotEmpty() && it != "null" },
        email = o.optString("email").takeIf { it.isNotEmpty() && it != "null" },
        address = o.optString("address").takeIf { it.isNotEmpty() && it != "null" },
        taxCode = o.optString("taxCode").takeIf { it.isNotEmpty() && it != "null" },
        paymentTerm = o.optString("paymentTerm").takeIf { it.isNotEmpty() && it != "null" },
        bankName = o.optString("bankName").takeIf { it.isNotEmpty() && it != "null" },
        bankAccount = o.optString("bankAccount").takeIf { it.isNotEmpty() && it != "null" },
        bankAccountHolder = o.optString("bankAccountHolder").takeIf { it.isNotEmpty() && it != "null" },
        notes = o.optString("notes").takeIf { it.isNotEmpty() && it != "null" },
        isActive = o.optBoolean("isActive", true),
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.optLong("createdAt", now),
        updatedAt = o.optLong("updatedAt", now),
        deviceId = deviceId,
    )

    private fun jsonToProductEntity(o: JSONObject, storeId: String, deviceId: String, now: Long) = ProductEntity(
        id = o.getString("id"),
        storeId = storeId,
        categoryId = o.optString("categoryId").takeIf { it.isNotEmpty() && it != "null" },
        supplierId = o.optString("supplierId").takeIf { it.isNotEmpty() && it != "null" },
        sku = o.getString("sku"),
        barcode = o.optString("barcode").takeIf { it.isNotEmpty() && it != "null" },
        name = o.getString("name"),
        description = o.optString("description").takeIf { it.isNotEmpty() && it != "null" },
        costPrice = o.optDouble("costPrice", 0.0),
        sellingPrice = o.optDouble("sellingPrice", 0.0),
        unit = o.optString("unit", "pcs"),
        imagePath = o.optString("imagePath").takeIf { it.isNotEmpty() && it != "null" },
        additionalImages = o.optString("additionalImages").takeIf { it.isNotEmpty() && it != "null" },
        minStock = o.optInt("minStock", 0),
        maxStock = o.optInt("maxStock", -1).takeIf { it >= 0 },
        isActive = o.optBoolean("isActive", true),
        trackInventory = o.optBoolean("trackInventory", true),
        taxRate = o.optDouble("taxRate", 0.0),
        hasVariants = o.optBoolean("hasVariants", false),
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.optLong("createdAt", now),
        updatedAt = o.optLong("updatedAt", now),
        deviceId = deviceId,
    )

    private fun jsonToVariantEntity(o: JSONObject, storeId: String, deviceId: String, now: Long) = ProductVariantEntity(
        id = o.getString("id"),
        storeId = storeId,
        productId = o.getString("productId"),
        variantName = o.getString("variantName"),
        sku = o.getString("sku"),
        barcode = o.optString("barcode").takeIf { it.isNotEmpty() && it != "null" },
        costPrice = o.optDouble("costPrice", Double.NaN).takeIf { !it.isNaN() },
        sellingPrice = o.optDouble("sellingPrice", Double.NaN).takeIf { !it.isNaN() },
        attributes = o.optString("attributes", "{}"),
        isActive = o.optBoolean("isActive", true),
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.optLong("createdAt", now),
        updatedAt = o.optLong("updatedAt", now),
        deviceId = deviceId,
    )

    private fun jsonToCustomerEntity(o: JSONObject, storeId: String, deviceId: String, now: Long) = CustomerEntity(
        id = o.getString("id"),
        storeId = storeId,
        name = o.getString("name"),
        phone = o.optString("phone").takeIf { it.isNotEmpty() && it != "null" },
        email = o.optString("email").takeIf { it.isNotEmpty() && it != "null" },
        address = o.optString("address").takeIf { it.isNotEmpty() && it != "null" },
        notes = o.optString("notes").takeIf { it.isNotEmpty() && it != "null" },
        totalSpent = o.optDouble("totalSpent", 0.0),
        visitCount = o.optInt("visitCount", 0),
        lastVisitAt = o.optLong("lastVisitAt", -1L).takeIf { it >= 0 },
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.optLong("createdAt", now),
        updatedAt = o.optLong("updatedAt", now),
        deviceId = deviceId,
    )

    private fun jsonToOrderEntity(o: JSONObject, storeId: String, deviceId: String) = OrderEntity(
        id = o.getString("id"),
        storeId = storeId,
        orderCode = o.getString("orderCode"),
        customerId = o.optString("customerId").takeIf { it.isNotEmpty() && it != "null" },
        customerName = o.optString("customerName").takeIf { it.isNotEmpty() && it != "null" },
        customerPhone = o.optString("customerPhone").takeIf { it.isNotEmpty() && it != "null" },
        subtotal = o.optDouble("subtotal", 0.0),
        discountType = o.optString("discountType").takeIf { it.isNotEmpty() && it != "null" },
        discountValue = o.optDouble("discountValue", 0.0),
        discountAmount = o.optDouble("discountAmount", 0.0),
        taxAmount = o.optDouble("taxAmount", 0.0),
        totalAmount = o.optDouble("totalAmount", 0.0),
        status = o.optString("status", "completed"),
        notes = o.optString("notes").takeIf { it.isNotEmpty() && it != "null" },
        createdBy = o.optString("createdBy", ""),
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.getLong("createdAt"),
        updatedAt = o.getLong("updatedAt"),
        deviceId = deviceId,
    )

    private fun jsonToOrderItemEntity(o: JSONObject, deviceId: String) = OrderItemEntity(
        id = o.getString("id"),
        orderId = o.getString("orderId"),
        productId = o.getString("productId"),
        variantId = o.optString("variantId").takeIf { it.isNotEmpty() && it != "null" },
        productName = o.getString("productName"),
        variantName = o.optString("variantName").takeIf { it.isNotEmpty() && it != "null" },
        quantity = o.getDouble("quantity"),
        unitPrice = o.getDouble("unitPrice"),
        costPrice = o.optDouble("costPrice", 0.0),
        discountType = o.optString("discountType").takeIf { it.isNotEmpty() && it != "null" },
        discountValue = o.optDouble("discountValue", 0.0),
        discountAmount = o.optDouble("discountAmount", 0.0),
        taxAmount = o.optDouble("taxAmount", 0.0),
        totalPrice = o.getDouble("totalPrice"),
        createdAt = o.getLong("createdAt"),
        updatedAt = o.getLong("updatedAt"),
        deviceId = deviceId,
    )

    private fun jsonToOrderPaymentEntity(o: JSONObject, deviceId: String) = OrderPaymentEntity(
        id = o.getString("id"),
        orderId = o.getString("orderId"),
        method = o.getString("method"),
        amount = o.getDouble("amount"),
        receivedAmount = o.optDouble("receivedAmount", Double.NaN).takeIf { !it.isNaN() },
        changeAmount = o.optDouble("changeAmount", 0.0),
        referenceNo = o.optString("referenceNo").takeIf { it.isNotEmpty() && it != "null" },
        notes = o.optString("notes").takeIf { it.isNotEmpty() && it != "null" },
        createdAt = o.getLong("createdAt"),
        updatedAt = o.getLong("updatedAt"),
        deviceId = deviceId,
    )

    private fun jsonToPurchaseOrderEntity(o: JSONObject, storeId: String, deviceId: String) = PurchaseOrderEntity(
        id = o.getString("id"),
        storeId = storeId,
        code = o.getString("code"),
        supplierId = o.optString("supplierId").takeIf { it.isNotEmpty() && it != "null" },
        supplierName = o.optString("supplierName").takeIf { it.isNotEmpty() && it != "null" },
        totalAmount = o.optDouble("totalAmount", 0.0),
        totalItems = o.optInt("totalItems", 0),
        notes = o.optString("notes").takeIf { it.isNotEmpty() && it != "null" },
        status = o.optString("status", "confirmed"),
        createdBy = o.optString("createdBy", ""),
        confirmedAt = o.optLong("confirmedAt", -1L).takeIf { it >= 0 },
        isDeleted = o.optBoolean("isDeleted", false),
        createdAt = o.getLong("createdAt"),
        updatedAt = o.getLong("updatedAt"),
        deviceId = deviceId,
    )

    private fun jsonToPurchaseOrderItemEntity(o: JSONObject, deviceId: String) = PurchaseOrderItemEntity(
        id = o.getString("id"),
        purchaseOrderId = o.getString("purchaseOrderId"),
        productId = o.getString("productId"),
        variantId = o.optString("variantId").takeIf { it.isNotEmpty() && it != "null" },
        productName = o.getString("productName"),
        variantName = o.optString("variantName").takeIf { it.isNotEmpty() && it != "null" },
        quantity = o.getDouble("quantity"),
        unitCost = o.getDouble("unitCost"),
        totalCost = o.getDouble("totalCost"),
        createdAt = o.getLong("createdAt"),
        updatedAt = o.getLong("updatedAt"),
        deviceId = deviceId,
    )
}

// ─── Result types ─────────────────────────────────────────────────────────────

sealed class BackupResult {
    data class Success(
        val filePath: String,
        val fileName: String,
        val createdAt: Long,
        val sizeBytes: Long,
    ) : BackupResult()
    data class Error(val message: String) : BackupResult()
}

sealed class RestoreResult {
    object Success : RestoreResult()
    data class Error(val message: String) : RestoreResult()
}

data class BackupFileInfo(
    val filePath: String,
    val fileName: String,
    val createdAt: Long,
    val sizeBytes: Long,
)
